/**:
  ros__parameters:
    frontend:
      color_image_topic: "color/image_raw"
      color_camera_info: "color/camera_info"
      depth_image_topic: "aligned_depth_to_color/image_raw"      
      odom_topic: "odom"
      sensor_type: "rgbd"
      inter_robot_loop_closure_budget: 1
      inter_robot_detection_period_sec: 1
      max_queue_size: 100
      similarity_threshold: 0.8
      global_descriptors_topic: "global_descriptors"
      image_crop_size: 376
      intra_loop_min_inbetween_keyframes: 8
      pnp_min_inliers: 100
      detection_publication_period_sec: 1.0
      detection_publication_max_elems_per_msg: 10
      enable_intra_robot_loop_closures: true
      keyframe_generation_ratio_threshold: 0.5
      use_vertex_cover_selection: true
      map_manager_process_period_ms: 100
      enable_sparsification: true
      global_descriptor_technique: "cosplace"
      nn_checkpoint: "models/resnet18_64.pth"
      cosplace:
        backbone: "resnet18"
        descriptor_dim: 64
    neighbor_management:
      enable_neighbor_monitoring: true
      max_heartbeat_delay_sec: 5.0
      init_delay_sec: 5.0
      heartbeat_period_sec: 1.0
    backend:
      pose_graph_optimization_start_period_ms: 10000
      pose_graph_optimization_loop_period_ms: 100
      max_waiting_time_sec: 60
      enable_broadcast_tf_frames: true
    evaluation:
      enable_logs: true
      log_folder: "results"
      enable_gps_recording: false
      gps_topic: "gps/fix"
      enable_sparsification_comparison: true
    visualization:
      enable: true
      publishing_period_ms: 500
      voxel_size: 0.2
      max_range: 4.0
